export const apiServiceMockResponse = {
  status: 'OK',
  copyright:
    'Copyright (c) 2023 The New York Times Company. All Rights Reserved.',
  section: 'home',
  last_updated: '2023-09-23T17:45:08-04:00',
  num_results: 4,
  results: [
    {
      section: 'us',
      subsection: 'politics',
      title: 'U.S. Provided Canada With Intelligence on Killing of Sikh Leader',
      abstract:
        'American intelligence gave assistance, but communications intercepted by Canada were more definitive in linking India to the killing of Hardeep Singh Nijjar.',
      url: 'https://www.nytimes.com/2023/09/23/us/politics/canada-sikh-leader-killing-intelligence.html',
      uri: 'nyt://article/d0d8396a-3a3d-5e76-ad44-fbf19fe8b8c6',
      byline: 'By Julian E. Barnes and Ian Austen',
      item_type: 'Article',
      updated_date: '2023-09-23T17:27:18-04:00',
      created_date: '2023-09-23T15:24:35-04:00',
      published_date: '2023-09-23T15:24:35-04:00',
      material_type_facet: '',
      kicker: '',
      des_facet: [
        'Assassinations and Attempted Assassinations',
        'United States International Relations',
        'Espionage and Intelligence Services',
        'Sikhs and Sikhism',
        'Secession and Independence Movements',
      ],
      org_facet: [],
      per_facet: ['Nijjar, Hardeep Singh (1977-2023)'],
      geo_facet: ['Canada', 'India'],
      multimedia: [
        {
          url: 'https://static01.nyt.com/images/2023/09/23/us/politics/23dc-intel/23dc-intel-superJumbo.jpg',
          format: 'Super Jumbo',
          height: 1364,
          width: 2048,
          type: 'image',
          subtype: 'photo',
          caption:
            'Demonstrators outside the Consulate General of India in Vancouver after the shooting of Hardeep Singh Nijjar, a Sikh separatist leader, in June. ',
          copyright: 'Ethan Cairns/The Canadian Press, via Associated Press',
        },
        {
          url: 'https://static01.nyt.com/images/2023/09/23/us/politics/23dc-intel/23dc-intel-threeByTwoSmallAt2X.jpg',
          format: 'threeByTwoSmallAt2X',
          height: 400,
          width: 600,
          type: 'image',
          subtype: 'photo',
          caption:
            'Demonstrators outside the Consulate General of India in Vancouver after the shooting of Hardeep Singh Nijjar, a Sikh separatist leader, in June. ',
          copyright: 'Ethan Cairns/The Canadian Press, via Associated Press',
        },
        {
          url: 'https://static01.nyt.com/images/2023/09/23/us/politics/23dc-intel/23dc-intel-thumbLarge.jpg',
          format: 'Large Thumbnail',
          height: 150,
          width: 150,
          type: 'image',
          subtype: 'photo',
          caption:
            'Demonstrators outside the Consulate General of India in Vancouver after the shooting of Hardeep Singh Nijjar, a Sikh separatist leader, in June. ',
          copyright: 'Ethan Cairns/The Canadian Press, via Associated Press',
        },
      ],
      short_url: 'https://nyti.ms/48luKmF',
    },
    {
      section: 'world',
      subsection: 'canada',
      title: 'Two Hooded Gunmen, a Silver Getaway Car and a Slain Sikh Leader',
      abstract:
        'Three witnesses who said they saw the killers of Hardeep Singh Nijjar, the Sikh leader at the center of a diplomatic dispute between Canada and India, described the scene.',
      url: 'https://www.nytimes.com/2023/09/23/world/canada/canada-india-sikhs.html',
      uri: 'nyt://article/bc63e487-56fa-514c-918b-e3d7a3e125c6',
      byline: 'By Norimitsu Onishi and Ian Austen',
      item_type: 'Article',
      updated_date: '2023-09-23T16:41:23-04:00',
      created_date: '2023-09-23T10:57:04-04:00',
      published_date: '2023-09-23T10:57:04-04:00',
      material_type_facet: '',
      kicker: '',
      des_facet: [
        'Sikhs and Sikhism',
        'Murders, Attempted Murders and Homicides',
        'Politics and Government',
        'International Relations',
      ],
      org_facet: [],
      per_facet: ['Nijjar, Hardeep Singh (1977-2023)', 'Trudeau, Justin'],
      geo_facet: [
        'British Columbia (Canada)',
        'Canada',
        'India',
        'Surrey (British Columbia)',
      ],
      multimedia: [
        {
          url: 'https://static01.nyt.com/images/2023/09/23/multimedia/23canada-sikh-sub-wfgj/23canada-sikh-sub-wfgj-superJumbo.jpg',
          format: 'Super Jumbo',
          height: 1365,
          width: 2048,
          type: 'image',
          subtype: 'photo',
          caption:
            'A memorial for Hardeep Singh Nijjar who was shot and killed in June outside the Guru Nanak Sikh Gurdwara in Surrey, British Columbia.',
          copyright: 'Jackie Dives for The New York Times',
        },
        {
          url: 'https://static01.nyt.com/images/2023/09/23/multimedia/23canada-sikh-sub-wfgj/23canada-sikh-sub-wfgj-threeByTwoSmallAt2X.jpg',
          format: 'threeByTwoSmallAt2X',
          height: 400,
          width: 600,
          type: 'image',
          subtype: 'photo',
          caption:
            'A memorial for Hardeep Singh Nijjar who was shot and killed in June outside the Guru Nanak Sikh Gurdwara in Surrey, British Columbia.',
          copyright: 'Jackie Dives for The New York Times',
        },
        {
          url: 'https://static01.nyt.com/images/2023/09/23/multimedia/23canada-sikh-sub-wfgj/23canada-sikh-sub-wfgj-thumbLarge.jpg',
          format: 'Large Thumbnail',
          height: 150,
          width: 150,
          type: 'image',
          subtype: 'photo',
          caption:
            'A memorial for Hardeep Singh Nijjar who was shot and killed in June outside the Guru Nanak Sikh Gurdwara in Surrey, British Columbia.',
          copyright: 'Jackie Dives for The New York Times',
        },
      ],
      short_url: 'https://nyti.ms/3LyfqJs',
    },
    {
      section: 'us',
      subsection: '',
      title:
        'The Wrecking-Ball Caucus: How the Far Right Brought Washington to Its Knees',
      abstract:
        'Right-wing Republicans who represent a minority in their party and in Congress have succeeded in sowing mass dysfunction, spoiling for a shutdown, an impeachment and a House coup.',
      url: 'https://www.nytimes.com/2023/09/23/us/republicans-congress-freedom-caucus.html',
      uri: 'nyt://article/d4962eca-661d-5dcc-9802-1488678256d1',
      byline: 'By Carl Hulse',
      item_type: 'Article',
      updated_date: '2023-09-23T15:27:44-04:00',
      created_date: '2023-09-23T05:01:22-04:00',
      published_date: '2023-09-23T05:01:22-04:00',
      material_type_facet: '',
      kicker: 'News Analysis',
      des_facet: [
        'United States Politics and Government',
        'Right-Wing Extremism and Alt-Right',
        'Impeachment',
        'Shutdowns (Institutional)',
      ],
      org_facet: [
        'House of Representatives',
        'Republican Party',
        'House Freedom Caucus',
        'Senate',
      ],
      per_facet: ['McCarthy, Kevin (1965- )', 'Good, Bob (1965- )'],
      geo_facet: [],
      multimedia: [
        {
          url: 'https://static01.nyt.com/images/2023/09/22/multimedia/00dc-repubs1-bmjw/00dc-repubs1-bmjw-superJumbo.jpg',
          format: 'Super Jumbo',
          height: 1366,
          width: 2048,
          type: 'image',
          subtype: 'photo',
          caption:
            'Representative Bob Good of Virginia, one of the Republican rebels, said he had had just one constituent express concern about a government shutdown.',
          copyright: 'Pool photo by Rod Lamkey',
        },
        {
          url: 'https://static01.nyt.com/images/2023/09/22/multimedia/00dc-repubs1-bmjw/00dc-repubs1-bmjw-threeByTwoSmallAt2X.jpg',
          format: 'threeByTwoSmallAt2X',
          height: 400,
          width: 600,
          type: 'image',
          subtype: 'photo',
          caption:
            'Representative Bob Good of Virginia, one of the Republican rebels, said he had had just one constituent express concern about a government shutdown.',
          copyright: 'Pool photo by Rod Lamkey',
        },
        {
          url: 'https://static01.nyt.com/images/2023/09/22/multimedia/00dc-repubs1-bmjw/00dc-repubs1-bmjw-thumbLarge.jpg',
          format: 'Large Thumbnail',
          height: 150,
          width: 150,
          type: 'image',
          subtype: 'photo',
          caption:
            'Representative Bob Good of Virginia, one of the Republican rebels, said he had had just one constituent express concern about a government shutdown.',
          copyright: 'Pool photo by Rod Lamkey',
        },
      ],
      short_url: 'https://nyti.ms/3ronlSQ',
    },
    {
      section: 'nyregion',
      subsection: '',
      title: 'Gold Bullion and Halal Meat: Inside the Menendez Investigation',
      abstract:
        'Federal prosecutors have accused Senator Robert Menendez of New Jersey and his wife, Nadine, of accepting bribes in exchange for official actions by Mr. Menendez.',
      url: 'https://www.nytimes.com/2023/09/23/nyregion/bob-menendez-indictment-bribery-investigation.html',
      uri: 'nyt://article/d9bb54c0-4e8c-55da-92aa-88b3416bf66f',
      byline: 'By Nicole Hong',
      item_type: 'Article',
      updated_date: '2023-09-23T10:10:07-04:00',
      created_date: '2023-09-23T03:00:26-04:00',
      published_date: '2023-09-23T03:00:26-04:00',
      material_type_facet: '',
      kicker: '',
      des_facet: [
        'Halal Foods and Products',
        'Foreign Aid',
        'Conflicts of Interest',
        'Ethics and Official Misconduct',
        'Bribery and Kickbacks',
        'Arms Trade',
        'United States Politics and Government',
      ],
      org_facet: [
        'IS EG Halal',
        'Justice Department',
        'Senate',
        'Senate Committee on Foreign Relations',
        'State Department',
      ],
      per_facet: [
        'Hana, Wael',
        'Menendez, Robert',
        'Menendez, Nadine',
        'Uribe, Jose D',
        'Daibes, Fred',
      ],
      geo_facet: [],
      multimedia: [
        {
          url: 'https://static01.nyt.com/images/2023/09/22/nyregion/00nj-menendez-01/00nj-menendez-01-superJumbo.jpg',
          format: 'Super Jumbo',
          height: 1366,
          width: 2048,
          type: 'image',
          subtype: 'photo',
          caption:
            'Senator Robert Menendez and his wife, Nadine, were charged in what federal prosecutors describe as a sprawling corruption scheme.',
          copyright: 'Chip Somodevilla/Getty Images',
        },
        {
          url: 'https://static01.nyt.com/images/2023/09/22/nyregion/00nj-menendez-01/00nj-menendez-01-threeByTwoSmallAt2X.jpg',
          format: 'threeByTwoSmallAt2X',
          height: 400,
          width: 600,
          type: 'image',
          subtype: 'photo',
          caption:
            'Senator Robert Menendez and his wife, Nadine, were charged in what federal prosecutors describe as a sprawling corruption scheme.',
          copyright: 'Chip Somodevilla/Getty Images',
        },
        {
          url: 'https://static01.nyt.com/images/2023/09/22/nyregion/00nj-menendez-01/00nj-menendez-01-thumbLarge.jpg',
          format: 'Large Thumbnail',
          height: 150,
          width: 150,
          type: 'image',
          subtype: 'photo',
          caption:
            'Senator Robert Menendez and his wife, Nadine, were charged in what federal prosecutors describe as a sprawling corruption scheme.',
          copyright: 'Chip Somodevilla/Getty Images',
        },
      ],
      short_url: 'https://nyti.ms/3Lyr3jJ',
    },
  ],
};
