export enum SectionSlug {
  Arts = 'arts',
  Automobiles = 'automobiles',
  BooksReview = 'books/review',
  Business = 'business',
  Fashion = 'fashion',
  Food = 'food',
  Health = 'health',
  Home = 'home',
  Insider = 'insider',
  Magazine = 'magazine',
  Movies = 'movies',
  NyRegion = 'nyregion',
  Obituaries = 'obituaries',
  Opinion = 'opinion',
  Politics = 'politics',
  Realestate = 'realestate',
  Science = 'science',
  Sports = 'sports',
  Sundayreview = 'sundayreview',
  Technology = 'technology',
  Theater = 'theater',
  TMagazine = 't-magazine',
  Travel = 'travel',
  Upshot = 'upshot',
  Us = 'us',
  World = 'world',
}
